config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'homes#index'
    get 'index',                    to: 'homes#index'
    get '/search',                  to: 'products#search'
    get '/cart',                    to: 'orders#edit'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'static_pages#about'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    post '/add_cart',               to: 'orders#add_cart'
    patch '/cart',                  to: 'orders#update'

    resources :products, only: [:show, :index]
    resources :categories, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_copy_right.html.erb
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Categories</h5>
            <%= taxons_menu(header: false) %>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
            <%= taxons_menu("brand", header: false) %>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<head>
  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag() %>

  <!-- PLUGINS CSS STYLE -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- GOOGLE FONT -->
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

  <!-- CUSTOM CSS -->
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css', :media => "all" %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

  <%= render 'layouts/shim.html.erb' %>
</head>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= form_tag potepan_search_path, method: :get do %>
                    <span class="input-group">
                      <%= text_field_tag('keyword', nil, placeholder:'Search...', class: 'form-control', 'aria-describedby' => 'basic-addon2') %>
                      <span class="input-group-addon">Search</span>
                    </span>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>
                <%= current_order.try(:display_total) || '$0' %>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <% if current_order.nil? || current_order.line_items.empty? %>
                  <li>カートに商品はありません</li>
                <% else %>
                  <li>カートに商品が <%= current_order.line_items.count %> 点あります</li>
                  <%= render partial: 'layouts/line_item', collection: current_order.line_items %>
                  <li>
                    <div class="btn-group" role="group" aria-label="...">
                      <%= button_tag type: 'button', onclick: "window.location.href='#{potepan_cart_path}'", class: 'btn btn-default' do %>
                        カートを見る
                      <% end %>
                      <button type="button" class="btn btn-default">購入する</button>
                    </div>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", alt: "", class: "navbar-brand"), potepan_path %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li class="active"><%= link_to "ALL PRODUCTS", potepan_category_path(Spree::Taxon.first.id, view: "grid") %></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><%= link_to "ALL PRODUCTS", potepan_category_path(Spree::Taxon.first.id, view: "list") %></li>
                  <li class="listHeading">Others</li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><%= link_to "About Us", potepan_about_us_path %></li>
              <li><%= link_to "Register", "#" %></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="lost-password.html">Password Recovery</a></li>
              <li><a href="privacy_policy.html">Privacy Policy</a></li>
              <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
              <li><a href="404.html">404 Not Found</a></li>
              <li><a href="coming-soon.html">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="account-dashboard.html">Dashboard</a></li>
              <li><a href="account-profile.html">Profile</a></li>
              <li><a href="account-all-orders.html">All Orders</a></li>
              <li><a href="account-single-order.html">Single Order</a></li>
              <li><a href="account-wishlist.html">Wishlist</a></li>
              <li><a href="account-address.html">Address</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_line_item.html.erb
<li>
  <%= link_to potepan_product_path(line_item.variant.product.slug) do %>
    <div class="media">
      <% if line_item.variant.images.length == 0 %>
        <%= image_tag(line_item.variant.product.display_image.attachment(:small), :class => "media-left media-object", width: '64px') %>
      <% else %>
        <%= image_tag(line_item.variant.images.first.attachment.url(:small), :class => "media-left media-object", width: '64px') %>
      <% end %>
      <div class="media-body">
        <h5 class="media-heading"><%= line_item.name %><br>
          <span><%= line_item.single_money.to_html %> X <%= line_item.quantity %></span>
        </h5>
      </div>
    </div>
  <% end %>
</li>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <form action="login-" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">メールアドレス</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">パスワード</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> 記憶しておく
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_sign_up_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header', collection: @root_taxons, as: :root_taxon %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/copy_right' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/sign_up_modal' %>
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>